name: Update Progress

on:
  push:
    paths:
      - README.md

jobs:
  progress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Calculate progress
        run: |
          TOTAL=$(grep -o "\- \[" README.md | wc -l)
          DONE=$(grep -o "\- \[x\]" README.md | wc -l)
          PERCENT=$((100 * DONE / TOTAL))
          FILLED=$((PERCENT / 5))
          EMPTY=$((20 - FILLED))
          BAR="$(printf "%0.s█" $(seq 1 $FILLED))$(printf "%0.s░" $(seq 1 $EMPTY))"

          sed -i "/<!-- PROGRESS-START -->/,/<!-- PROGRESS-END -->/c\
          <!-- PROGRESS-START -->\n\
          **Completed:** $DONE / $TOTAL  \n\
          **Progress:** **$PERCENT%**\n\n\
          \`\`\`\n\
          $BAR $PERCENT%\n\
          \`\`\`\n\
          <!-- PROGRESS-END -->" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update progress" || echo "No changes"
          git push
